name: "Pull Request Labeler"

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/configs/labeler.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true